application:
    defaultMessage: this was configured via a config service instance and configuration repository!
    dumpMessage: the hits are viewable in the logs!

spring:
  datasource:
    driverClassName: org.h2.Driver
  data:
    redis:
      repositories:
        enabled: false
  autoconfigure:
    exclude:
      - com.microsoft.azure.spring.autoconfigure.cosmosdb.CosmosDbRepositoriesAutoConfiguration
      - com.microsoft.azure.spring.autoconfigure.cosmosdb.CosmosAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  session:
    store-type: none