application:
  defaultMessage: this is using redis profile and sessions are enabled!
  dumpMessage: the hits are viewable in the logs!

spring:
  data:
    redis:
      repositories:
        enabled: true
  autoconfigure:
    exclude:
      - com.microsoft.azure.spring.autoconfigure.cosmosdb.CosmosDbRepositoriesAutoConfiguration
      - com.microsoft.azure.spring.autoconfigure.cosmosdb.CosmosAutoConfiguration
    include:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  session:
    store-type: redis